# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BitbucketAsList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BitbucketAsList
  pod 'ProgressHUD'
  
  pod 'ReachabilitySwift'

  target 'BitbucketAsListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BitbucketAsListUITests' do
    # Pods for testing
  end

end
